### ISSUE TITLE
udev alias - ConBee II detected as RasBee

### ISSUE THREAD

**Issue by lenisko** [marthoc/hassio-addons#106]
I have a problem with making things shine & clean.

Currently to my rpi I have connected two sticks **zwave** and **zigbee**. Looks like order of those devices for `/dev/ttyACM*` is random.
As you already guessed at this point, I have problem with setting them correctly.

What I did was an udev rule, to pin `/dev/zigbee` and `/dev/zwave` aliases.

Now.. the problem is, that `/dev/zigbee` is not detected correctly by docker, it's showing up as RasBee and can't connect.

Any workarounds? or ideas for that? Maybe there's a way to pin those devices to own `/dev/ttyACM*` or something.

Creating alias as `/dev/ttyACM11` pointing to zigbee device is not working as well, device is detected as ConBee II though.
```
...
22:20:56:394 COM: --dev: /dev/ttyACM12 (ConBee II)
22:20:57:360 dev /dev/ttyAMA0
22:20:57:360 COM: --dev: /dev/ttyACM12 (ConBee II)
22:20:57:392 dev /dev/ttyAMA0
22:20:57:392 COM: --dev: /dev/ttyACM12 (ConBee II)
22:20:58:366 dev /dev/ttyAMA0
22:20:58:366 COM: --dev: /dev/ttyACM12 (ConBee II)
22:20:58:399 dev /dev/ttyAMA0
22:20:58:399 COM: --dev: /dev/ttyACM12 (ConBee II)
22:20:59:365 dev /dev/ttyAMA0
22:20:59:365 COM: --dev: /dev/ttyACM12 (ConBee II)
22:20:59:397 dev /dev/ttyAMA0
```

```
crw-rw----    1 root     dialout   166,   0 May 18 20:19 /dev/ttyACM0
crw-rw----    1 root     dialout   166,   1 May 18 20:19 /dev/ttyACM1
lrwxrwxrwx    1 root     root             7 May 18 20:19 /dev/ttyACM11 -> ttyACM0
lrwxrwxrwx    1 root     root             7 May 18 20:19 /dev/ttyACM12 -> ttyACM1
```

**Comment by quentinsf** [comment]
I had the same issue, but I thought it was that the symlink to the device wasn't available inside the container, and the system just defaulted to assuming a Raspbee?

In my case, I'd like to have:

`/dev/conbee -> ttyUSB1`

which is set up by udev on the host machine, but I need to work out how to mount that symlink inside the container.  Is there an official way to do this?

In the early days, docker allowed single files to be mounted as 'volumes', but I think that mounts now need to be a directory.

The other way to solve my problem would be to mount `/dev/serial/by-id` (which *is* a directory) within the container, since I can also get a stable link from there.

Is there a way to add to the volumes mounted within an add-on's container?

**Comment by lenisko** [comment]
Idea with mounting `/dev/serial/by-id` or even device itself would be great. 
Right now it looks almost like device recognition is made on path to tty device.

**Comment by marthoc** [comment]
As far as I know Hass.io doesn't allow for predictable naming of devices at the moment. See e.g. https://github.com/home-assistant/hassio/issues/1111. Once Hass.io supports predictable device naming, this problem will be solved by using /dev/serial/by-id entries since those are static.

**Comment by lenisko** [comment]
It's already merged into `Hass.io supervisor 167`.
