### ISSUE TITLE
Error after update to 2.05.39

### ISSUE THREAD

**Issue by eskimos2000** [marthoc/hassio-addons#21]
Hi,

It worked perfectly well (raspbee on rpi3) but ufter last update it is gone, I have error:
`ERROR (MainThread) [hassio.addons.addon] Addon 69bb46cb_deconz have wrong options: Missing required option 'deconz_device'. Got {'deconz_device': None, 'web_port': 8080, 'websockets_port': 8443, 'debug_info': 1, 'debug_aps': 0, 'debug_zcl': 0, 'debug_zdp': 0, 'debug_otau': 0}`

Phoscan is not responsive and crap, to be honest.  It means I have to go to rest option again?
Help, please.

**Comment by eskimos2000** [comment]
Ok I needed to add co config: 
`"deconz_device": "/dev/ttyAMA0"` for raspbee

I should read instruction but was so unexpected, thx for aarch64 support, I will try it soon.

**Comment by jeena** [comment]
I have the same problem and the same change helped. But it would have been nice if it would find the device dynamically so if the path changes it still can be found.

**Comment by marthoc** [comment]
I did add a note to the readme so that it would show up in the instructions for the addon and also document it in the changelog. Not sure how much more explicit I can be but glad you figured it out. 

Unfortunately because of the way deCONZ finds the device, there’s no auto detect. That has to come from deCONZ. The way it used to work was just to look for AMA0 or USB0 and not work if RaspBee or Conbee wasn’t one of those. 

You MAY be able to specify the name of the device from /dev/serial/by-id, which would be an unchanging name. I say MAY because I haven’t investigated HassOS and if it creates these symlinks. Try it and let me know if it works!

**Comment by BoneheadFraggle** [comment]
Thanks for this!

As a reply to "Not sure how much more explicit", well, one way is to explain HOW you do it.
An example is probaly the easiest way.

Something like this in the changelog:
Require deCONZ device to be specified in config. (like "deconz_device": "/dev/ttyAMA0" for RaspBee or "deconz_device": "/dev/ttyUSB0" for Conbee).

Probably a good thing to add it in the add-on description too.

Anyway - thank you for the add-on, it works great!
I wish we could handle Telldus devices the same way.

**Comment by eskimos2000** [comment]
As @BoneheadFraggle mentioned examples work best for noobs like me;-), So it is a good way to avoid a bit upgrade disaster. Anyway, thank for the great job man.

**Comment by marthoc** [comment]
I'm going to update the readme to make it more clear. Thanks for the Issue. Closing.
