### ISSUE TITLE
VNC not starting on Hass.IO

### ISSUE THREAD

**Issue by corvy** [marthoc/hassio-addons#62]
I have updated the config as indicated in the new default config but the VNC server does still not start up. 

See the following screenshot. 

![unnamed](https://user-images.githubusercontent.com/138292/51208701-b2b5b480-190e-11e9-913b-af912e70ffaa.png)

Also tried to connect from VNC and telnet the 5900 port on Hass.IO but connection denied.

**Comment by pergolafabio** [comment]
i also have issues after updating to .55 , my phoscon website even doesnt start anymore, cant access it anymore, also using hassio addon
does your page at :8080 still works?

i have this in log files now

2019-01-15 21:58:58 ERROR (MainThread) [pydeconz.utils] Error getting deCONZ data from http://192.168.0.17:8080/api/5F713DB88F.
2019-01-15 21:58:58 ERROR (MainThread) [pydeconz] Couldn't load data from deCONZ
2019-01-15 21:58:58 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway. Retrying in 256 seconds

**Comment by corvy** [comment]
Yeah, just tried phoscon and it fails too. No devices show up in hass.io either. Seems to be some problem with this release and it seems to be run.sh and config related (guessing here!!)

**Comment by pergolafabio** [comment]
fiew, ok, its not me 
how can we easy rollback?

**Comment by corvy** [comment]
Phoscon seems to be running on port 80 here. Have you tried that?

**Comment by pergolafabio** [comment]
yes, i can now enter phoscon app on 80 , strange , it was always 8080 as default, also in the config its still there as 8080 : 

 "web_port": 8080,

**Comment by pergolafabio** [comment]
after restart of hassio, i still see in log that it wants to connect to 8080 , although i changed webport to 80 now in json config

2019-01-15 23:06:47 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway. Retrying in 8 seconds
2019-01-15 23:06:56 ERROR (MainThread) [pydeconz.utils] Error getting deCONZ data from http://192.168.0.17:8080/api/5F713DB88F.

so still not working :(

**Comment by corvy** [comment]
Yeah I cannot get connected Hass to deconz... So now I control lights in phoscon it seems....

**Comment by pergolafabio** [comment]
ok, i deleted the integration, changed now to 80 in json confg, the authenticated the conbee again
so up and running
but phoscon is still on 80 , should be on 8080 , like in config
so i think it seems hardcoded now somewhere

VNC still not running though, while its enabled to true

**Comment by forast3r** [comment]
Similar issue here, but I have detected that in my case it is using port 443 (instead of 8443 as stated in the config)

addon log:
`[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.55
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyUSB0
/run.sh: 33: [: :true: unexpected operator
[Hass.io] Starting in minimal mode, without VNC GUI
libpng warning: iCCP: known incorrect sRGB profile`

Hassio log:
`19-01-15 22:18:08 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on marthoc/hassio-addon-deconz-amd64 with version 2.05.55
19-01-15 22:18:09 WARNING (MainThread) [hassio.api.security] No API token provided for /api/config`

**Comment by r0l01** [comment]
Have the same issue with deCONZ using port 80.

Restored deCONZ 2.05.54 from snapshot.    - No luck.

Then tried a "restore selected" with everything selected. Had to upgrade Hass to 0.85.1 since the snapshot contained HA  0.84.6.    - Problem still persists. 

So the hardcoding of ports seems to be done in files that are not restorable with the snapshot function.

**Comment by corvy** [comment]
> ok, i deleted the integration, changed now to 80 in json confg, the authenticated the conbee again
> so up and running
> but phoscon is still on 80 , should be on 8080 , like in config
> so i think it seems hardcoded now somewhere
> 
> VNC still not running though, while its enabled to true

Thanks for this tip! Had to change the websock port to 443 as well to get it to work. NB! I had port 80 open in firewall due to letsencrypt renewals. Had to lose this, might be relevant for more people. Seems also the problem is identified: 
https://github.com/marthoc/docker-deconz/issues/91

**Comment by corvy** [comment]
VNC starts after last merge!

**Comment by corvy** [comment]
But it still runs on port 80, not respecting the config for port 8080.

**Comment by pergolafabio** [comment]
Strange, should be fixed also? I have read somewhere .. so we need another new bug fix?

**Comment by corvy** [comment]
Just created a new issue. This is closed. I just connected to VNC and it works fine!
